# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import icon
from PyQt5 import QtCore, QtGui, QtWidgets

from out import Ui_OutputDialog

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(972, 767)
        Form.setStyleSheet("#Form{background-color:qlineargradient(spread:pad, x1:0.199, y1:0.165, x2:1, y2:1, stop:0.0635593 rgba(0, 0, 0, 255), stop:0.822034 rgba(0, 64, 67, 255));}")
        self.label_user = QtWidgets.QLabel(Form)
        self.label_user.setGeometry(QtCore.QRect(360, 300, 71, 21))
        self.label_user.setObjectName("label_user")
        self.label_mdp = QtWidgets.QLabel(Form)
        self.label_mdp.setGeometry(QtCore.QRect(360, 440, 91, 21))
        self.label_mdp.setObjectName("label_mdp")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(420, 610, 131, 41))
        self.pushButton.setStyleSheet("border-color: rgb(254, 255, 242);\n"
"font: 75 10pt \"Berlin Sans FB\";\n"
"background-color: qconicalgradient(cx:0.479, cy:0.403, angle:0, stop:0.949153 rgba(206, 241, 202, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.label_img = QtWidgets.QLabel(Form)
        self.label_img.setGeometry(QtCore.QRect(360, 20, 231, 221))
        self.label_img.setStyleSheet("background-image: url(:/newPrefix/usthb.jpg);\n"
"border-color: rgb(139, 168, 153);")
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.label_error = QtWidgets.QLabel(Form)
        self.label_error.setGeometry(QtCore.QRect(350, 550, 271, 31))
        self.label_error.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.input_user = QtWidgets.QLineEdit(Form)
        self.input_user.setGeometry(QtCore.QRect(360, 330, 241, 61))
        self.input_user.setStyleSheet("color: rgb(170, 170, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(0, 0,0,0);")
        self.input_user.setObjectName("input_user")
        self.input_mdp = QtWidgets.QLineEdit(Form)
        self.input_mdp.setGeometry(QtCore.QRect(360, 470, 241, 61))
        self.input_mdp.setStyleSheet("color: rgb(170, 170, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(0, 0,0,0);")
        self.input_mdp.setText("")
        self.input_mdp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_mdp.setObjectName("input_mdp")
        self.label_img.raise_()
        self.label_user.raise_()
        self.label_mdp.raise_()
        self.pushButton.raise_()
        self.label_error.raise_()
        self.input_user.raise_()
        self.input_mdp.raise_()
        self.pushButton.clicked.connect(self.gologin)
        self._new_window = None

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_user.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">User</span></p></body></html>"))
        self.label_mdp.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">mot de passe</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Demarrer"))
        self.pushButton.setShortcut(_translate("Form", "Return"))
        self.input_user.setText(_translate("Form", "admin"))
    def gologin(self):
               
                # if self.input_user.text()=="admin" and self.input_mdp.text()=="pass":               
                if self.input_user.text()=="admin":               
                    Form.hide()  # hide the main window
                    # self.outputWindow_()  # Create and open new output window
                    self._new_window = Ui_OutputDialog()
                    self._new_window.show()
                    self._new_window.startVideo("0")
                    self._new_window.connect()
                elif  self.input_user.text()=="" or self.input_mdp.text()=="":
                        self.label_error.setText("   merci de remplir les champs")

                else:
                        self.label_error.setText("username or password non valide")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
